---
title: "Open Data Imports"
author: "Ben Keel"
date: "2023-02-14"
output: html_document
---

Package Set Up

```{r Set Up}

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning=FALSE)
knitr::opts_chunk$set(message=FALSE)

library(tidyverse)
library(tidycensus)
library(kableExtra)
library(caret)
library(knitr) 
library(pscl)
library(plotROC)
library(pROC)
library(lubridate)
library(broom)
library(stargazer)
library(ggplot2)
library(gridExtra)
library(janitor)
library(sf)
library(viridis)
library(data.table)
library(boxr)
library(lubridate)

options(scipen=999)
options(tigris_class = "sf")
 
g<-glimpse

source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")

crs <- "EPSG:4326"
PHL_crs <- 'ESRI:102411' #This measurement-based CRS projection is for the West Coast


census_api_key("3c9540be1434ac4b38e6e55d60e8ee95909f2254", overwrite = TRUE)

palletteO <- c("#fef0d9","#fdcc8a","#fc8d59","#e34a33","#b30000")


palette5 <- c("#981FAC","#CB0F8B","#FF006A","#FE4C35","#FE9900")
palette4 <- c("#981FAC","#FF006A","#FE4C35","#FE9900")
palette2 <- c("#981FAC","#FF006A")
palette_9_colors <- c("#FF2AD4","#E53AD8","#CC4ADC","#996AE5","#7F7BE9",
                      "#668BED","#33ABF6","#19BBFA","#00CCFF")
palette_3_colors <- c("#FF2AD4","#7F7BE9","#00CCFF")
palette_2_colors <- c("#FF2AD4", "#00CCFF")
palette_1_colors <- c("#00CCFF")

```

Trying to set up a panel

```{r Panel Set Up}

quarter <- c("Q1", "Q2", "Q3", "Q4")
year <- c(2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022)

frame <- data.frame(year, quarter)

comb <- expand.grid(year = year, quarter = quarter)%>%
  mutate(yq = paste(year, ":", quarter))%>%
  mutate(yqDT = yq(yq))%>%
  arrange(yqDT)

g(comb)

panel <- as_tibble(comb)%>%
  dplyr::select(yqDT)
  
g(comb)

panel

```


ACS geometry of Philadelphia

```{r ACS Data Loading}

acs_vars <- c("B01001_001E")

acsTractsPHL.2020 <- get_acs(geography = "tract",
                             year = 2020, 
                             variables = acs_vars, 
                             geometry = TRUE, 
                             state = "PA", 
                             county = "Philadelphia", 
                             output = "wide")%>%
  st_set_crs("EPSG:4326")

  

```

Importing OPA Data

```{r OPA Upload and building counts}

#Data from https://www.opendataphilly.org/dataset/opa-property-assessments

#metadata at: https://metadata.phila.gov/#home/datasetdetails/5543865f20583086178c4ee5/representationdetails/55d624fdad35c7e854cb21a4/?view_287_page=3

AllOPA <- read_csv("D:/MUSA/MUSASpring/M8040_Practicum/Data/OpenDataPhilly-opa_properties_public.csv")

OPA_sf <- AllOPA%>%
  drop_na(lng, lat)%>%
  st_as_sf(coords = c("lng", "lat"),
           crs = "EPSG:4326")

g(OPA_sf)

```

Reducing OPA Data to relevant items

```{r OPA data reduction}

OPA_sf_small <- OPA_sf %>%
  dplyr::select(location, category_code, category_code_description, building_code, building_code_description, building_code_new, building_code_description_new, total_area, total_livable_area, owner_1, owner_2, market_value, market_value_date, number_of_bedrooms, number_of_bathrooms, number_stories, interior_condition, assessment_date, year_built, year_built_estimate, zoning, quality_grade)%>%
  rename(address = location)%>%
  filter(category_code == 1 | 
         category_code == 2 |
         category_code == 3)


g(OPA_sf_small)

g(OPA_sf_small)

OPA_address <- OPA_sf_small%>%
  dplyr::select(address)%>%
  st_drop_geometry()




```

Create OPA panel

```{r}

panelOPA <- expand.grid(address = OPA_address$address, 
             quarter = panel$yqDT)

```

Loading Fire Data

```{r Loading and Cleaning Fire, message=FALSE, warning=FALSE}

#Box Upload Philadelphia Structure Fire


structureFire_sf <- structureFire%>%
  drop_na(Longitude, Latitude)%>%
  st_as_sf(coords = c("Longitude", "Latitude"),
           crs = "EPSG:4326")%>%
  clean_names

#Conversion to address, with changes from AV to AVE
structureFire_sf_address <-
  structureFire_sf %>%
  mutate(street_type = ifelse(street_type == 'AV', "AVE", street_type))%>%
  unite(address, c(address_number, street_prefix, street_name, street_type), sep = " ", remove = TRUE, na.rm=TRUE)

#Taking out duplicate incident numbers
structureFire_sf_addressU <- 
    structureFire_sf_address[!duplicated(structureFire_sf_address$incident_number),]

g(structureFire_sf_addressU)

sfs_sf_addU_fsna <- filter(structureFire_sf_addressU, is.na(fire_spread)==TRUE)
table(sfs_sf_addU_fsna$incident_type)

```

counting Fires per Quarter

```{r}

#Creating panel of fire counts for each address in each quarter
count.panel <- 
  structureFire_sf_addressU %>%
  mutate(quarter = as_date(floor_date(alarm_date, unit="quarter")))%>%
  st_drop_geometry() %>%
  group_by(quarter, address) %>% 
  count(address, sort=TRUE)%>%
  rename(n_Fires = n)

count.panel$address <-
  as.factor(count.panel$address)

g(count.panel)

table(count.panel$quarter)
table(panelOPA$quarter)
g(panelOPA)

```

Combining Fire with OPA

```{r}

# Joining the other data
panel_OPAFire <- left_join(panelOPA, count.panel, by=c("address", "quarter")) # Join


panel_OPAFire$n_Fires[is.na(panel_OPAFire$n_Fires)] <- 0

filter(panel_OPAFire, address == "5600 OGONTZ AVE")%>%
  ggplot(aes(quarter, n_Fires))+
    geom_col()

g(panel_OPAFire)

```

311 Call data

```{r loading 311 data, echo=FALSE}

#311 Data Upload, downloaded from https://data.phila.gov/visualizations/311-requests/

All311 <- read_csv("D:/MUSA/MUSASpring/M8040_Practicum/Data/OpenDataPhilly-311Calls.csv")

g(All311)

```

Filtering 311 Data to the appropriate categories

``` {r 311 filter}

#Filtering to only the fire/building-relevant terms

property311 <- filter(All311, 
                        #service_name == "Building Dangerous" |  
                        #service_name == "Dangerous Building Complaint " |  
                        #service_name == "Fire Safety Complaint" | 
                        #service_name == "Maintenance Complaint" |
                        #service_name == "Maintenance Residential or Commercial" |
                        service_name == "Vacant House or Commercial" ) %>%
                        #service_name == "Fire Residential or Commercial" |
                        #service_name == "Complaints against Fire or EMS"
                      
  dplyr::select(objectid, service_request_id, status, service_name, service_code, requested_datetime, agency_responsible, address, zipcode, lat, lon)%>%
  drop_na(lat, lon, address)%>%
  st_as_sf(coords = c("lon", "lat"),
           crs = "EPSG:4326")

prop311_small <- property311%>%
  dplyr::select(service_name, requested_datetime, address)%>%
  st_drop_geometry()%>%
  mutate(quarter = floor_date(requested_datetime, unit="quarter"))

vacant311_count <- prop311_small%>%
  group_by(address, quarter)%>%
  count(address, sort=TRUE)%>%
  rename(n_311Vacant = n)
  
g(property311)



```

``` {r 311 Property Stuff}
property311%>%
filter(address == "1756 N TANEY ST")

```


Importing Permit Data

```{r Permit Data}

#Data from https://www.opendataphilly.org/dataset/licenses-and-inspections-building-permits

#metadata at: https://metadata.phila.gov/#home/datasetdetails/5543868920583086178c4f8f/representationdetails/5e9a01ac801624001585ca11/

permits0715 <- read_csv("D:/MUSA/MUSASpring/M8040_Practicum/Data/OpenDataPhilly-permits_0715.csv")
permits1623 <- read_csv("D:/MUSA/MUSASpring/M8040_Practicum/Data/OpenDataPhilly-permits_1623.csv")

permitsAll <- rbind(permits0715, permits1623)

permits_sf <- permitsAll%>%
  drop_na(lng, lat)%>%
  st_as_sf(coords = c("lng", "lat"),
           crs = "EPSG:4326")

```

Cleaning Permit Data and Creating Count Table

```{r Permit Data Clean and Count}

permits_sf_res <- permits_sf%>%
  dplyr::select(permittype, permitdescription, permitissuedate, commercialorresidential, address)%>%
#  filter(permitdescription == "DEMOLITION PERMIT" |
#         permitdescription == "GENERAL PERMIT" |
#         permitdescription == "NEW CONTRUCTION PERMIT" |
#         permitdescription == "RESIDENTIAL BUILDING PERMIT" |
#         permitdescription == "FAST FORM BUILDING PERMIT" |
#         permitdescription == "ALTERATION PERMIT")%>%
  filter(commercialorresidential != "COMMERICAL")%>%
  mutate(quarter = as_date(floor_date(permitissuedate, unit="quarter")))%>%
  filter(year(quarter) >= 2009)

permits_count <- permits_sf_res %>%
  st_drop_geometry()%>%
  group_by(address, quarter)%>%
  count(address, sort = TRUE)%>%
  rename(n_permits = n)

g(permits_count)

```

Joining 

```{r Join 311 and Permits to panel_FireOPA}

panel_OPAFire311 <- left_join(panel_OPAFire, vacant311_count, by=c("address", "quarter"))

panel_OPAFire311$n_311Vacant[is.na(panel_OPAFire311$n_311Vacant)] <- 0

panel_OPAFire311Permit <- left_join(panel_OPAFire311, permits_count, by=c("address", "quarter"))

panel_OPAFire311Permit$n_permits[is.na(panel_OPAFire311Permit$n_permits)] <- 0

```


```{r Calculate 6 months after}

p <- days(200)
iSample <- interval(ymd("2017-07-01"), ymd("2017-07-01") + p)

g(panel_taney)
#if there is a fire, is there a non-zero value in the column within that row or the following row

panel_taney2 <- panel_taney %>%
  mutate(days = (quarter + days(1)) %within% interval(quarter, quarter + p))

panel_taney2 <- panel_taney %>%
  mutate(fire = quarter %within% iSample)

#get the vacancy 311 sum for all observations within the interval
panel_taney2 <- panel_taney %>%
  mutate(dateSpan = interval(quarter, quarter + p),
         fireVacancy = sum(filter(panel_taney, quarter %within% dateSpan)$n_311Vacant))

panel_taney2 <- panel_taney %>%
  mutate(vacant =

dplyr::select(filter(panel_taney$quarter %within% interval(quarter, quarter + p)),n_311Vacant)

  mutate(vacant_180 = ifelse(n_Fires > 0,
                        ifelse(sum(filter(panel_OPAFire311Permit$address == address,
                                          panel_OPAFire311Permit$quarter %within% 
                                            (quarter + p))$n_311Vacant
                                   )>0, 1), 
                        0))


```
